import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author user
 */
public class UTS extends javax.swing.JFrame {

      
String keranjangpesanan ="";
int totalharga = 0;
        private String isipesanan;
    /**
     * Creates new form UTS
     */
    public UTS() {
        initComponents();
        dropdown_kategori.removeAllItems();
        dropdown_kategori.addItem("Makanan");
        dropdown_kategori.addItem("Minuman");
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        dropdown_kategori = new javax.swing.JComboBox<>();
        reset_button = new javax.swing.JButton();
        jumlahpesanan_field = new javax.swing.JTextField();
        total_field = new javax.swing.JTextField();
        nama_field1 = new javax.swing.JTextField();
        harga_field = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listmenu = new javax.swing.JList<>();
        pesan_button1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        keranjangpesanan_field = new javax.swing.JTextArea();
        total_button = new javax.swing.JButton();
        nomeja_field2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 255));
        setSize(new java.awt.Dimension(5, 6));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("APLIKASI PEMESANAN MAKANAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(82, 6, 260, 20);

        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("No. Meja ");
        getContentPane().add(label1);
        label1.setBounds(21, 53, 57, 20);

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("Nama");
        getContentPane().add(label2);
        label2.setBounds(20, 90, 37, 20);

        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setText("Kategori");
        getContentPane().add(label3);
        label3.setBounds(20, 130, 53, 20);

        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setText("Menu");
        getContentPane().add(label4);
        label4.setBounds(20, 160, 36, 20);

        label5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label5.setText("Jumlah Pesanan");
        getContentPane().add(label5);
        label5.setBounds(10, 290, 100, 20);

        dropdown_kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdown_kategoriActionPerformed(evt);
            }
        });
        getContentPane().add(dropdown_kategori);
        dropdown_kategori.setBounds(110, 130, 280, 22);

        reset_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reset_button.setText("Reset");
        reset_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(reset_button);
        reset_button.setBounds(280, 470, 72, 23);

        jumlahpesanan_field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jumlahpesanan_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahpesanan_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(jumlahpesanan_field);
        jumlahpesanan_field.setBounds(110, 290, 100, 22);

        total_field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        total_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(total_field);
        total_field.setBounds(110, 320, 71, 22);

        nama_field1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nama_field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_field1ActionPerformed(evt);
            }
        });
        getContentPane().add(nama_field1);
        nama_field1.setBounds(110, 90, 71, 22);

        harga_field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        harga_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(harga_field);
        harga_field.setBounds(220, 290, 100, 22);

        listmenu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listmenu.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listmenuValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listmenu);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(110, 160, 280, 110);

        pesan_button1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pesan_button1.setText("Pesan");
        pesan_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesan_button1ActionPerformed(evt);
            }
        });
        getContentPane().add(pesan_button1);
        pesan_button1.setBounds(100, 470, 72, 23);

        keranjangpesanan_field.setColumns(20);
        keranjangpesanan_field.setRows(5);
        jScrollPane1.setViewportView(keranjangpesanan_field);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 360, 380, 86);

        total_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        total_button.setText("Total");
        total_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(total_button);
        total_button.setBounds(10, 320, 72, 23);

        nomeja_field2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nomeja_field2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeja_field2ActionPerformed(evt);
            }
        });
        getContentPane().add(nomeja_field2);
        nomeja_field2.setBounds(110, 50, 71, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reset_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_buttonActionPerformed
        keranjangpesanan ="";
        totalharga = 0;
        keranjangpesanan_field.setText("");
        total_field.setText("");
        nama_field1.setText("");
        nomeja_field2.setText("");
        jumlahpesanan_field.setText("");
        harga_field.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_reset_buttonActionPerformed

    private void dropdown_kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdown_kategoriActionPerformed
  String kategori=String.valueOf(dropdown_kategori.getSelectedItem());
        String[]data = null;
        if(kategori.equals("Makanan")){
            data = new String[]{"Nasi Goreng Spesial","Ayam Lada Hitam","Ayam BBQ","Seafood Asam Manis","Fuyunghai"};
        }
        else if(kategori.equals("Minuman")){
            data = new String[]{"Americano","Cappucino", "Lemon Tea","Lychee Tea", "Matcha Latte", "Air Mineral"};
        }
        listmenu.setListData(data);        // TODO add your handling code here:
    }//GEN-LAST:event_dropdown_kategoriActionPerformed

    private void total_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_fieldActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_total_fieldActionPerformed

    private void nama_field1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_field1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_field1ActionPerformed

    private void jumlahpesanan_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahpesanan_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahpesanan_fieldActionPerformed

    private void harga_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harga_fieldActionPerformed

    private void listmenuValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listmenuValueChanged
String menu=listmenu.getSelectedValue();
        if (menu !=null){
            int harga = 0;
           switch (menu.toLowerCase()){
                case "bakso" -> harga = 15000;
                case "nasi goreng spesial" -> harga = 20000;
                case "ayam lada hitam" -> harga = 25000;
                case "ayam bbq" -> harga = 24000;
                case "ayam mentega" -> harga = 24000;
                case "americano" -> harga = 15000;
                case "cappucino" -> harga = 13000;
                case "lemon tea" -> harga = 12000;
                case "lemon" -> harga = 12000;
                case "matcha latte" -> harga = 12000;
                case "dimsum" -> harga = 20000;
                case "churros" -> harga = 12000;
                case "sweet corn" -> harga = 13000;
                case "salad buah" -> harga = 15000;
            }
        harga_field.setText("Rp " + harga); 
        }       // TODO add your handling code here:
    }//GEN-LAST:event_listmenuValueChanged

    private void pesan_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesan_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesan_button1ActionPerformed

    private void nomeja_field2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeja_field2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeja_field2ActionPerformed

    private void total_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_buttonActionPerformed
       Object selectedMenu = listmenu.getSelectedValue();
    String jumlahpesanan = jumlahpesanan_field.getText();

    if (selectedMenu != null && !jumlahpesanan.isEmpty()) {
        try {
            String menu = selectedMenu.toString();
            int jumlah = Integer.parseInt(jumlahpesanan);
            int harga = 0;

           switch (menu.toLowerCase()){
                case "bakso" -> harga = 15000;
                case "nasi goreng spesial" -> harga = 20000;
                case "ayam lada hitam" -> harga = 25000;
                case "ayam bbq" -> harga = 24000;
                case "ayam mentega" -> harga = 24000;
                case "americano" -> harga = 15000;
                case "cappucino" -> harga = 13000;
                case "lemon tea" -> harga = 12000;
                case "lemon" -> harga = 12000;
                case "matcha latte" -> harga = 12000;
                case "dimsum" -> harga = 20000;
                case "churros" -> harga = 12000;
                case "sweet corn" -> harga = 13000;
                case "salad buah" -> harga = 15000;
            }

            int subTotal = harga * jumlah;
            keranjangpesanan += menu + " (" + jumlah + "x) = Rp " + subTotal + "\n";

            totalharga += subTotal;
            keranjangpesanan_field.setText((keranjangpesanan));

            total_field.setText("Rp " + totalharga);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Isi jumlah dengan angka!");
        }
    }
}

private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {
    keranjangpesanan = "";
    // Tambahkan kode reset field lainnya di sini jika diperlukan, contoh:
    // totalHarga = 0;
    // keranjang_field.setText("");
    // total_field.setText("");
}    // TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_total_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set Nimbus look and feel */
    
    /* Tampilkan Form */
        java.awt.EventQueue.invokeLater(new Runnable() {
          @Override
          public void run() {
              new UTS().setVisible(true);
          }
      });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> dropdown_kategori;
    private javax.swing.JTextField harga_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlahpesanan_field;
    private javax.swing.JTextArea keranjangpesanan_field;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private javax.swing.JList<String> listmenu;
    private javax.swing.JTextField nama_field1;
    private javax.swing.JTextField nomeja_field2;
    private javax.swing.JButton pesan_button1;
    private javax.swing.JButton reset_button;
    private javax.swing.JButton total_button;
    private javax.swing.JTextField total_field;
    // End of variables declaration//GEN-END:variables

